apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namspace: roboshop
  #replica set labels
  labels:
    project: roboshop
    app: nginx
    tier: database
spec:
  replicas: 1 #we can give number here as many as we want
  # These are the labels replicaset uses to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: mongodb
      project: roboshop
      tier: database
    # this is pod defination
  template:
    metadata:
      labels:
        purpose: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: karna0323/mongodb:v2
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports: 
  - protocol: TCP
    port: 27017 #service port
    targetPort: 27017 # container port