apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namspace: roboshop
  #replica set labels
  labels:
    project: roboshop
    app: nginx
    tier: app
spec:
  replicas: 1 #we can give number here as many as we want
  # These are the labels replicaset uses to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: catalogue
      project: roboshop
      tier: app
    # this is pod defination
  template:
    metadata:
      labels:
        purpose: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
      - name: catalogue
        image: karna0323/catalogue:v2
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: app
  ports: 
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 # container port